version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgresqldb:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build:
      context: .
      target: dev
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=$POSTGRES_PORT
    expose:
      - 3001
    ports:
      - 3001:3001
    volumes:
      - .:/app
    stdin_open: true
    tty: true
volumes:
  postgresqldb:
    driver: local
